- learn-ts/package.json
> Init: Typescript folder create

- learn-ts/.gitignore
- learn-ts/package.json
- learn-ts/src/01/index.ts
- learn-ts/src/01/main.js
- learn-ts/tsconfig.json
**오늘의 학습 내용 정리**
main.js → javascript 필수 문법
index.ts → typescript 기본 타입
> [FE5_김은지] 20250407_01_과제제출

- .gitignore
- learn-ts/package.json
- learn-ts/src/01/01.md
- learn-ts/src/01/index.ts
- learn-ts/src/01/main.js
- learn-ts/tsconfig.json
- 오늘 배운 내용 정리를 추가로 md 파일로 진행해봤습니다.
> [FE5_이재건] 20250407_01_과제제출

- .gitignore
- learn-ts/package.json
- learn-ts/src/01/01.md
- learn-ts/src/01/index.html
- learn-ts/src/01/index.ts
- learn-ts/src/01/main.js
- learn-ts/tsconfig.json
> [FE5_박준규] 20250407_01_과제제출

- learn-ts/.gitignore
- learn-ts/package.json
- learn-ts/src/01/index.ts
- learn-ts/src/01/main.js
- learn-ts/tsconfig.json
- TypeScript 환경 세팅 / 정리
- .gitignore 추가
> [FE5_조정우] 20250407_01_과제제출

- learn-ts/package.json
- learn-ts/src/01/index.html
- learn-ts/src/01/index.ts
- learn-ts/src/01/main.js
- learn-ts/tsconfig.json
> [FE5_권태훈] 20250407_01_과제제출

- learn-ts/index.html
- learn-ts/package.json
- learn-ts/src/01/index.ts
- learn-ts/src/01/main.js
- learn-ts/tsconfig.json
JavaScript 필수 문법 및 TypeScript 기본 타입
> [FE5_한유빈] 20250407_01_과제제출

- learn-ts/index.html
- learn-ts/package.json
- learn-ts/src/01/index.ts
- learn-ts/src/01/main.js
- learn-ts/tsconfig.json
- 타입스크립트 설정
- 타입스크립트 개념 
- 타입스크립트를 배우기 위한 JS 정리
> [FE5_황수지] 20250407_01_과제제출

- learn-ts/.gitignore
- learn-ts/package.json
- learn-ts/src/01/index.ts
- learn-ts/src/01/main.js
- learn-ts/tsconfig.json
오늘 배운 사항 정리
javascript 필수 문법 정리 -> main.js
TS 기초 타입 -> index.ts
ps: 15시 부터 16시 까지 외출이었다 보니 다른분들께 물어보고 진행 했습니다.
> [FE5_박상윤] 20250407_01_과제제출

- .gitignore
- learn_ts/src/01/index.ts
> [FE5_이준호] 20250407_01_과제제출

- learn-js/01/index.html
- learn-js/01/main.js
- learn-ts/src/01/index.ts
- learn-ts/src/02/1.ts
- learn-ts/src/02/2.ts
- learn-ts/src/02/3.ts
- learn-ts/src/02/test-level1.ts
- learn-ts/src/02/test-level2.ts
- learn-ts/src/02/test-level3.ts
-  js보강 내용
- 기본 타입 연습문제
- 강의 메모
> [FE5_조정우] 20250408_01_과제제출

- learn-ts/src/02/0408.ts
- learn-ts/src/02/1.ts
- learn-ts/src/02/2.ts
- learn-ts/src/02/3.ts
- learn-ts/src/02/4.ts
- learn-ts/src/02/5.ts
- learn-ts/src/practice/기본 타입/Lv0.ts
- learn-ts/src/practice/기본 타입/Lv1.ts
- learn-ts/src/practice/기본 타입/Lv2.ts
> [FE5_이교은] 20250408_01_과제제출

- learn-ts/src/02/0408복습.ts
- learn-ts/src/02/2.ts
- learn-ts/src/02/3.ts
- learn-ts/src/02/4.ts
- learn-ts/src/02/5.ts
- learn-ts/src/02/index.ts
- learn-ts/src/02/연습문제++.ts
- learn-ts/src/02/연습문제+.ts
- learn-ts/src/02/연습문제.ts
> [FE5_남윤서] 20250408_02_과제제출

- learn-ts/.vscode/settings.json
- learn-ts/src/02/index.ts
- learn-ts/src/02/practice01.ts
- learn-ts/src/02/practice02.ts
- learn-ts/src/02/practice03.ts
> [FE5_조소정] 20250408_01_과제제출

- learn-ts/src/02/1.ts
- learn-ts/src/02/2.ts
- learn-ts/src/02/3.ts
- learn-ts/src/02/practice.ts
> [FE5_이서영] 20250408_01_과제제출

- learn-ts/src/02/1.ts
- learn-ts/src/02/2.ts
- learn-ts/src/02/3.ts
- learn-ts/src/02/basic_p1.ts
- learn-ts/src/02/basic_p2.ts
- learn-ts/src/02/basic_p3.ts
- 금일 자바스크립트 기본 자료형에 대한 연습문제 풀이입니다.
> [FE5_이재건] 20250408_01_연습문제풀이

- .gitignore
- learn-ts/package.json
- learn-ts/src/01/index.ts
- learn-ts/src/01/main.js
- learn-ts/src/02/1.ts
- learn-ts/src/02/2.ts
- learn-ts/src/02/3.ts
- learn-ts/src/02/practice.ts
- learn-ts/tsconfig.json
> [FE5_최원일] 20250408_01_과제제출

- learn-ts/src/02/1.ts
- learn-ts/src/02/2.ts
- learn-ts/src/02/test1.ts
- learn-ts/src/02/test2.ts
> [FE5_박은서]20250408_01_과제제출

- .gitignore
- learn-js/01/main.js
- learn-js/index.html
- learn-js/과제/JS01.js
- learn-js/과제/JS02.js
- learn-ts/src/01/index.ts
- learn-ts/src/02/1.ts
- learn-ts/src/02/2.ts
- learn-ts/src/02/4.ts
- learn-ts/src/02/5.ts
- learn-ts/src/02/연습문제++.ts
- learn-ts/src/02/연습문제+.ts
- learn-ts/src/02/연습문제.ts
> [FE5_황수지] 20250408_01_과제제출

- learn-ts/src/02/1.ts
- learn-ts/src/02/2.ts
- learn-ts/src/02/3.ts
- learn-ts/src/02/4.ts
- learn-ts/src/02/5.ts
- learn-ts/src/02/practice0.ts
- learn-ts/src/02/practice1.ts
- learn-ts/src/02/practice2.ts
> [FE5_한유빈] 20250408_01_연습문제제출

- learn-ts/src/02/01_type.ts
- learn-ts/src/02/index.ts
> [FE5_박상윤] 20250408_01_연습문제제출

- learn-ts/src/01/index.ts
- learn-ts/src/02/1.ts
- learn-ts/src/02/2.ts
- learn-ts/src/02/3.ts
- learn-ts/src/02/4.ts
- learn-ts/src/02/5.ts
- learn-ts/src/02/example.ts
> [FE5_권태훈] 20250408_연습문제제출

- learn-ts/src/02/practice1.ts
- learn-ts/src/03/1.ts
- learn-ts/src/03/2.ts
- learn-ts/src/03/3.ts
- learn-ts/src/03/ex01.ts
TypeScript 3일차 함수 수업 및 연습문제 풀이
> [FE5_한유빈] 20250409_01_과제제출

- learn-ts/src/02/index.ts
- learn-ts/src/02/index2.ts
> [FE5_조소정] 20250408_02_과제제출

- learn-ts/src/02/02.md
- learn-ts/src/02/4.ts
- learn-ts/src/02/5.ts
> [FE5_이재건] 20250408_01_과제제출

- learn-js/01/index.html
- learn-js/01/main.js
- learn-js/01/연습 문제/condition.js
- learn-js/01/연습 문제/loop.js
- learn-ts/src/03/4.ts
- learn-ts/src/03/6.ts
ts 과제 제출 및 js 연습 문제 5까지 풀이하였습니다.
> [FE5_박은서] 20250410_01_과제제출

- learn-ts/src/03/1.ts
- learn-ts/src/03/2.ts
- learn-ts/src/03/3.ts
- learn-ts/src/03/4.ts
- learn-ts/src/03/5.ts
- learn-ts/src/03/6.ts
- learn-ts/src/03/7.ts
- learn-ts/src/03/practice01.ts
- learn-ts/src/03/practice02.ts
- learn-ts/src/03/practice03.ts
- learn-ts/src/03/practice04.ts
> [FE5_조소정] 20250409_01_과제제출

- learn-ts/src/03/1.ts
- learn-ts/src/03/2.ts
- learn-ts/src/03/3.ts
- learn-ts/src/03/4.ts
- learn-ts/src/03/5.ts
- learn-ts/src/03/6.ts
- learn-ts/src/03/7.ts
- learn-ts/src/03/8.ts
- learn-ts/src/03/example.ts
- learn-ts/src/03/example2.ts
함수 타입, 함수 타입+, 오퍼레이터, 오퍼레이터+ 연습 문제 풀이
> [FE5_권태훈] 20250409_01_과제제출 

- learn-ts/src/03/1.ts
- learn-ts/src/03/2.ts
- learn-ts/src/03/3.ts
- learn-ts/src/03/4.ts
- learn-ts/src/03/5.ts
- learn-ts/src/03/6.ts
- learn-ts/src/03/7.ts
- learn-ts/src/03/타입오퍼레이터연습문제.ts
- learn-ts/src/03/함수연습문제+.ts
- learn-ts/src/03/함수연습문제.ts
> [FE5_황수지] 20250409_01_과제제출

- learn-ts/src/02/6.ts
- learn-ts/src/02/basic_p2.ts
- learn-ts/src/02/basic_p3.ts
- learn-ts/src/03/1.ts
- learn-ts/src/03/2.ts
- learn-ts/src/03/3.ts
- learn-ts/src/03/4.ts
- learn-ts/src/03/5.ts
- learn-ts/src/03/6.ts
- learn-ts/src/03/7.ts
- learn-ts/src/03/func_p1.ts
- learn-ts/src/03/func_p2.ts
- 03/func_p1.ts => 함수 타입 문제 연습
- 03/func_p2.ts => 함수 타입 문제 연습+
시간 관계상, 오퍼레이션 타입 문제는 풀지 못해서 익일에 풀 예정입니다.
> [FE5_이재건] 20250409_01_과제제출

- .gitignore
- learn-ts/src/02/4.ts
- learn-ts/src/02/5.ts
- learn-ts/src/02/practice.ts
- learn-ts/src/03/1.ts
- learn-ts/src/03/2.ts
- learn-ts/src/03/3.ts
- learn-ts/src/03/4.ts
- learn-ts/src/03/5.ts
- learn-ts/src/03/6.ts
- learn-ts/src/03/7.ts
- learn-ts/src/03/ex1.ts
- learn-ts/src/03/ex2.ts
- learn-ts/src/03/ex3.ts
- learn-ts/src/03/ex4.ts
> [FE5_최원일] 20250409_01_과제제출

- learn-js/01/ex01.js
- learn-js/01/main.js
- learn-js/index.html
- learn-ts/src/03/4.ts
- learn-ts/src/03/5.ts
- learn-ts/src/03/6.ts
- learn-ts/src/03/7.ts
- learn-ts/src/03/ex01.ts
- learn-ts/src/03/ex02.ts
JavaScript 1일차 수업 및 연습문제 풀이
TypeScript 함수 타입 및 타입 오퍼레이터 연습문제 풀이
> [FE5_한유빈] 20250409_02_과제제출

- learn-js/JS복습/반복문연습문제.js
- learn-js/JS복습/변수연습문제.js
- learn-js/JS복습/연산자연습문제.js
- learn-js/JS복습/자료형연습문제.js
- learn-js/JS복습/조건문연습문제.js
- learn-js/JS복습/함수연습문제++.js
- learn-js/JS복습/함수연습문제+.js
- learn-js/JS복습/함수연습문제.js
- learn-ts/src/03/1.ts
- learn-ts/src/03/2.ts
- learn-ts/src/03/3.ts
- learn-ts/src/03/4.ts
- learn-ts/src/03/5.ts
- learn-ts/src/03/6.ts
- learn-ts/src/03/7.ts
- learn-ts/src/03/연습문제++.ts
- learn-ts/src/03/연습문제.ts
> [FE5_김보민] 20250408_01_JS연습문제 과제제출

- .gitignore
- learn-ts/src/03/test2.ts
- learn-ts/src/04/1.ts
- learn-ts/src/04/2.ts
- learn-ts/src/04/3.ts
- learn-ts/src/04/4.ts
- learn-ts/src/04/5.ts
- learn-ts/src/04/6.ts
- learn-ts/src/04/7.ts
- learn-ts/src/04/test/interface+.ts
- learn-ts/src/04/test/interface.ts
interface 
interface +
operator +
연습 문제 풀이
> [FE5_박은서] 20250411_01_과제제출

- learn-ts/src/04/1.ts
- learn-ts/src/04/2.ts
- learn-ts/src/04/3.ts
- learn-ts/src/04/4.ts
- learn-ts/src/04/5.ts
- learn-ts/src/04/6.ts
- learn-ts/src/04/7.ts
- learn-ts/src/04/Inter_example.ts
- learn-ts/src/04/Type_example.ts
> [FE5_권태훈] 20250410_01_과제제출

- learn-ts/src/03/practice_04.ts
- learn-ts/src/04/1.ts
- learn-ts/src/04/2.ts
- learn-ts/src/04/3.ts
- learn-ts/src/04/4.ts
- learn-ts/src/04/5.ts
- learn-ts/src/04/6.ts
- learn-ts/src/04/7.ts
- learn-ts/src/04/practice_01.ts
- learn-ts/src/04/practice_02.ts
- learn-ts/src/04/practice_03.ts
* 함수 타입 연습문제+
* 타입 오퍼레이터 연습문제
* 타입 오퍼레이터 연습문제+
* 인터페이스 연습문제
* 타입 별칭 연습문제
* 이넘 연습문제
> [FE5_이서영] 20250410_01_과제제출

- learn-ts/src/04/01.ts
- learn-ts/src/04/02.ts
- learn-ts/src/04/03.ts
- learn-ts/src/04/04.ts
- learn-ts/src/04/05.ts
- learn-ts/src/04/06.ts
- learn-ts/src/04/07.ts
- learn-ts/src/04/오퍼레이터연습문제.ts
- learn-ts/src/04/인터페이스연습문제.ts
연습문제는 오퍼레이터 연습문제, 인터페이스 연습문제 제출합니다..
> [FE5_김보민] 20250410_01_과제제출

- learn-ts/src/03/func_p2.ts
- learn-ts/src/03/oper_p1.ts
- learn-ts/src/03/oper_p2.ts
- learn-ts/src/04/1.ts
- learn-ts/src/04/2.ts
- learn-ts/src/04/3.ts
- learn-ts/src/04/4.ts
- learn-ts/src/04/5.ts
- learn-ts/src/04/6.ts
- learn-ts/src/04/7.ts
- learn-ts/src/04/inf_p1.ts
- oper_p1.ts, oper_p2.ts: 어제의 오퍼레이터 연습 문제 풀이
- inf_p1.ts: 인터페이스 연습 문제 풀이
> [FE5_이재건] 20250410_01_과제제출

- learn-ts/src/04/1.ts
- learn-ts/src/04/2.ts
- learn-ts/src/04/3.ts
- learn-ts/src/04/4.ts
- learn-ts/src/04/5.ts
- learn-ts/src/04/6.ts
- learn-ts/src/04/7.ts
- learn-ts/src/04/enum_quiz+.ts
- learn-ts/src/04/interface_quiz.ts
- learn-ts/src/04/type_quiz.ts
> [FE5_최원일] 20250410_01_과제제출

- learn-ts/src/04/1.ts
- learn-ts/src/04/2.ts
- learn-ts/src/04/3.ts
- learn-ts/src/04/4.ts
- learn-ts/src/04/5.ts
- learn-ts/src/04/6.ts
- learn-ts/src/04/7.ts
- learn-ts/src/04/이넘문제+.ts
- learn-ts/src/04/인터페이스문제.ts
- learn-ts/src/04/타입별칭문제.ts
>  [FE5_황수지] 20250410_01_과제제출

- .gitignore
- learn-js/03/1.js
- learn-ts/src/04/test/enum.ts
- learn-ts/src/04/test/generic.ts
- learn-ts/src/04/test/type-alias+.ts
- learn-ts/src/04/test/type-alias.ts
- learn-ts/src/05/01.ts
- learn-ts/src/05/02.ts
- learn-ts/src/05/03.ts
- learn-ts/src/05/04.ts
- learn-ts/src/05/06.ts
- learn-ts/src/05/07.ts
- learn-ts/src/05/08.ts
- learn-ts/src/05/09.ts
type alias
type alias +
enum
generic 연습 문제 풀이 제출
> [FE5_박은서] 20250414_01_연습 문제 풀이 제출

- learn-ts/src/04/practice_04.ts
- learn-ts/src/05/0.js
- learn-ts/src/05/1.ts
- learn-ts/src/05/2.ts
- learn-ts/src/05/3.ts
- learn-ts/src/05/4.ts
- learn-ts/src/05/5.ts
- learn-ts/src/05/6.ts
- learn-ts/src/05/7.ts
- learn-ts/src/05/8.ts
- learn-ts/src/05/9.ts
- learn-ts/src/05/practice_01.ts
- learn-ts/src/05/practice_02.ts
> [FE5_이서영] 20250413_01_과제제출

- learn-ts/src/03/타임오퍼레이터연습문제+.ts
- learn-ts/src/03/함수연습문제+.ts
> [FE5_황수지] 20250413_01_연습문제제출

- learn-js/.gitignore
- learn-js/02/main.js
- learn-js/03/main.js
- learn-js/eslint.config.mjs
- learn-js/index.html
- learn-js/package.json
- learn-ts/src/04/01_interface.ts
- learn-ts/src/04/02_interface.ts
- learn-ts/src/04/03_type_alias.ts
- learn-ts/src/04/04_type_alias.ts
- learn-ts/src/04/05_enum.ts
- learn-ts/src/04/06_enum.ts
- learn-ts/src/04/3.ts
- learn-ts/src/04/4.ts
- learn-ts/src/04/5.ts
- learn-ts/src/04/index.ts
- learn-ts/src/04/interface.ts
- learn-ts/src/05/01_generics.ts
- learn-ts/src/05/02_generics.ts
- learn-ts/src/05/03_class.ts
- learn-ts/src/05/1.ts
- learn-ts/src/05/2.ts
- learn-ts/src/05/3.ts
- learn-ts/src/05/4.ts
- learn-ts/src/05/5.ts
- learn-ts/src/05/6.ts
- learn-ts/src/05/7.ts
- learn-ts/src/05/8.ts
- learn-ts/src/05/9.ts
JS 보충 강의 내용 정리
TS 강의 내용 정리
TS 연습 문제 풀이
01, 02 interface
03, 04 type alias
05, 06 enum
> [FE5_박상윤] 20250410_01_과제제출

- learn-react/04/1/ex/3/src/components/LoginCard.tsx
- learn-react/04/1/ex/3/src/components/SignupCard.tsx
> [FE5_박준규] 20250417_01_과제제출

- learn-react/06_assignment/src/App.tsx
- learn-react/06_assignment/src/Components/Login.tsx
- learn-react/06_assignment/src/Components/SignIn.tsx
- learn-react/06_assignment/src/Components/html/Button.tsx
- learn-react/06_assignment/src/Components/html/CheckBox.tsx
- learn-react/06_assignment/src/Components/html/Input.tsx
- learn-react/06_assignment/src/css/tailwind.css
React 과제 컴포넌트 분리하여 수정하였습니다.
learn-react/06_assignment
> [FE5_박은서] 20250420_01_과제제출
